### ISSUE TITLE
Not sure, but the tarballs for 13.12 and 14.08 seem to be exactly the same to me - byte-for-byte

### ISSUE THREAD

**Issue by scumola** [sm0svx/svxlink-sounds-en_US-heather#3]
The two tarballs seem to be the same, and are also named the same but are in different directories.  Using the 'cmp' command, they test to be exactly the same binary file byte-for-byte.

https://github.com/sm0svx/svxlink-sounds-en_US-heather/releases/download/13.12.1/svxlink-sounds-en_US-heather-16k-13.12.tar.bz2

https://github.com/sm0svx/svxlink-sounds-en_US-heather/releases/download/14.08/svxlink-sounds-en_US-heather-16k-13.12.tar.bz2

**Comment by sm0svx** [comment]
Very old issue but anyway... Yes, they are the same since nothing changed between those two releases. Confusing naming I agree but it's all in order.
