### ISSUE TITLE
think sampelrate is worng

### ISSUE THREAD

**Issue by sa2blv** [sm0svx/svxlink-sounds-en_US-heather#4]
*** WARNING: SvxLink can only handle WAV files which have a sample rate of 16000. This file use 22050: /usr/share/svxlink/sounds/en_US/Core/talk_group.wav
*** WARNING: Illegal WAV file header in "/usr/share/svxlink/sounds/en_US/Default/0.wav". "fmt" subchunk size is not 16: /usr/share/svxlink/sounds/en_US/Default/0.wav

**Comment by sm0svx** [comment]
https://github.com/sm0svx/svxlink-sounds-en_US-heather/blob/master/README.md

**Comment by Ederion70** [comment]
Hi,
I'd like to change the file greeting.wav but I'm not able to use the script to transform the raw audio in a file ok for svxlink.
Where can I find a tutorial to use the script?
Thank you very much!!
