### ISSUE TITLE
10 phonetic soundfiles format mismatch

### ISSUE THREAD

**Issue by DK1LO** [sm0svx/svxlink-sounds-en_US-heather#5]
Unsigned 8 bit, Rate 8000 Hz, Mono
en_US/Default/phonetic_0.wav' : Unsigned 8 bit, Rate 8000 Hz, Mono
.....
en_US/Default/phonetic_9.wav' : Unsigned 8 bit, Rate 8000 Hz, Mono

all others file a correct
en_US/Default/phonetic_z.wav' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono

**Comment by sm0svx** [comment]
Seem to be ok in both the latest release and in the pre-release archives.
