### ISSUE TITLE
Fixed link to latest release please

### ISSUE THREAD

**Issue by oxoocoffee** [sm0svx/svxlink-sounds-en_US-heather#6]
Hello,

I am writing svx setup/installation/update script for OrangePi Zero(first) and would like to add link to your repository so sounds can be installed and configured. 
I did look for a fixed link to "the Latest" but, I can not find it. Would it be possible to have something like
https://github.com/sm0svx/svxlink-sounds-en_US-heather/releases/download/svxlink-sounds-en_US-heather-16k.tar.bz2 so my script can always depend on it? Perhaps add README.me inside with the release version?

Thank you

Robert

**Comment by sm0svx** [comment]
Try to use the GitHub API:
```
curl -sH "Accept: application/vnd.github.v3+json" https://api.github.com/repos/sm0svx/svxlink-sounds-en_US-heather/releases/latest | jq -r '.assets[].browser_download_url'
```
